### ISSUE TITLE
libdevice not found during training using default conda environment on Ubuntu 22.04.2 with a RTX A4000

### ISSUE THREAD

**Issue by phcavelar** [microsoft/molecule-generation#61]
Hello, just to let you know that when running `molecule-generation train` following the `Readme.md`, with the default conda environment, on Ubuntu 22.04.2 with a RTX A4000 fails by not finding libdevice, log below.

I've found that pinning Tensorflow to version 2.10 instead of 2.11 (latest version and installed automatically at time of writing) [as per this stackoverflow question](https://stackoverflow.com/questions/75037100/libdevice-not-found-tensorflow) fixes it.

If you wish, I can open a PR to pin the TF version to 2.10 until this is fixed upstream, or else I'm at least posting this here so that other people can find this error and solution more easily.

```sh
Avg weighted sum. of graph losses:  291.5334
Avg weighted sum. of prop losses:   0.5965
Avg node class. loss:                 71.0492
Avg first node class. loss:           40.7059
Avg edge selection loss:              1.7546
Avg edge type loss:                   4.0202
Avg attachment point selection loss:  1.1500
Avg KL divergence:                    6981316.0000
Property results: sa_score: MAE 10.77, MSE 3818.02 (norm MAE: 13.31) | clogp: MAE 23.54, MSE 13726.24 (norm MAE: 12.95) | mol_weight: MAE 393.53, MSE 168733.92 (norm MAE: 3.57).
   (Stored model metadata and weights to ~/data/moler/saved/GNN_Edge_MLP_MoLeR__2023-06-21_09-51-05_best.pkl).
2023-06-21 09:52:54.588760: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.595713: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.612998: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.618529: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.647620: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.663816: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.683986: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.702780: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.723474: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-06-21 09:52:54.741439: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/phcavelar/miniconda3/envs/moler-env/bin/molecule_generation", line 8, in <module>
    sys.exit(main())
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/cli.py", line 35, in main
    run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/cli.py", line 35, in <lambda>
    run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/train.py", line 179, in run_from_args
    trained_model_path = train(
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/train.py", line 274, in train
    train_loss, train_speed, train_results = model.run_on_data_iterator(
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/models/moler_base_model.py", line 244, in run_on_data_iterator
    task_metrics = self._run_step(batch_features, batch_labels, training)
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tf2_gnn/models/graph_task_model.py", line 336, in _run_step
    return self._fast_run_step(batch_features_tuple, batch_labels_tuple, training)
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'cond/StatefulPartitionedCall_122' defined at (most recent call last):
    File "/home/phcavelar/miniconda3/envs/moler-env/bin/molecule_generation", line 8, in <module>
      sys.exit(main())
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/cli.py", line 35, in main
      run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
      func()
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/cli.py", line 35, in <lambda>
      run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/train.py", line 179, in run_from_args
      trained_model_path = train(
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/cli/train.py", line 252, in train
      _, _, initial_valid_results = model.run_on_data_iterator(
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/molecule_generation/models/moler_base_model.py", line 244, in run_on_data_iterator
      task_metrics = self._run_step(batch_features, batch_labels, training)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tf2_gnn/models/graph_task_model.py", line 336, in _run_step
      return self._fast_run_step(batch_features_tuple, batch_labels_tuple, training)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tf2_gnn/models/graph_task_model.py", line 363, in _fast_run_step
      tf.cond(training, true_fn=_training_update, false_fn=_no_op)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tf2_gnn/models/graph_task_model.py", line 357, in _training_update
      self._apply_gradients(zip(gradients, self.trainable_variables))
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/tf2_gnn/models/graph_task_model.py", line 324, in _apply_gradients
      self._optimizer.apply_gradients(gradient_variable_pairs)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/phcavelar/miniconda3/envs/moler-env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'cond/StatefulPartitionedCall_122'
libdevice not found at ./libdevice.10.bc
	 [[{{node cond/StatefulPartitionedCall_122}}]] [Op:__inference__fast_run_step_84892]
```

**Comment by kmaziarz** [comment]
Does this happen only on very specific machines? Is it considered a bug in `tensorflow` that is expected to be fixed in a future version? I'm wondering what is the right course of action for us, given that `environment.yml` is also used in CI (and the versions are unpinned there to detect when newest `tensorflow` breaks our code)...

**Comment by phcavelar** [comment]
I don't know how specific this would be to Ubuntu or to the GPU I was running on, since the Stackoverflow question doesn't specify which GPU they had when that problem started.

However, I saw that [the only CI job that uses TF 2.11](https://github.com/microsoft/molecule-generation/actions/runs/5292544792/jobs/9579550164) installs the CPU version of Tensorflow:
```
     + tensorflow                       2.11.1  cpu_py310hd1aba9c_0      conda-forge       31kB
``` 

Which might be the reason why the CI pipeline isn't catching the problem. I understand that it might not be practical to run a CI job with a machine with a GPU, but, if you have the resources for it, it might something to consider, since the code in this repo is most likely going to be ran with a GPU and it is exactly my GPU setup that failed. This will allow you be able to catch these nasty CUDA-related bugs by doing so, at least so that people are aware of which versions might fail in the future.

For now, I think just having this thread might be enough to help anyone that stumbles upon this issue, but it'd be even better to put it as a warning on the readme as some people might not always look up past issues before opening a new one.

**Comment by kmaziarz** [comment]
> I saw that [the only CI job that uses TF 2.11](https://github.com/microsoft/molecule-generation/actions/runs/5292544792/jobs/9579550164) installs the CPU version of Tensorflow

Yes, I guess that's expected; I wouldn't expect the standard CI agents to have a GPU. That being said, I noticed that the Python 3.8 build seems to be installing CUDA libraries and GPU-enabled Tensorflow... I need to take a closer look to understand what's going on here.

Coming back to your issue, the [Tensorflow install guide](https://www.tensorflow.org/install/pip#step-by-step_instructions) has a section called "Ubuntu 22.04" which seems to talk about the exact problem you're having? They mention a way to fix it which does not involve downgrading Tensorflow. If this is indeed a fix, then maybe I can mention that in the `README.md` explicitly (we already point to the Tensorflow website for guidelines on installation, just without specific details).

**Comment by kmaziarz** [comment]
(For me the instructions from the Tensorflow website resolve the issue, and training under `2.13.0` seems to be working)
